# exception1.py

print("Exception1")
10*(1/0)                #ZeroDivisionError: division by zero
print("program exit")