# exception2.py

print("Exception2")
4+spam*3            #NameError: name 'spam' is not defined
print("program exit")